INHERIT: mkdocs.yml

plugins:
  - search
  - tags # Insiders
  - git-revision-date


# Long explanation for this extra doc. 
# In order to use config inheritance, everything must use the alternative syntax (key:value vs lists)
# Lists are replaced wholesale with config inheritence. 
# I couldn't get alternative syntax to work on mkdocs.yml without throwing constant errors and strange behavior.
# For now, mkdocs.yml plugins need to be all NON-insiders plugins, and insiders.mkdocs.yml is ALL plugins. 
