# Project information
site_name: Amplitude Developer Doc
site_url: https://developer.amplitude.com
site_author: Amplitude
site_description: >-
  Get your digital optimization going with the Amplitude developer center. Put real words here. 
# Repository
repo_name: Amplitude-Developer-Docs/amplitude-dev-center
repo_url: https://github.com/Amplitude-Developer-Docs/amplitude-dev-center
edit_uri: "blob/main/docs/"

# Copyright
copyright: Copyright &copy; 2022 Amplitude

# Configuration
theme:
  name: material
  custom_dir: overrides


  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    #- announce.dismiss # this feature is perenially buggy, so keep it disabled unless necessary.
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    #- navigation.expand
    - navigation.indexes
    #- navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate #this is a really noisy feature, IMO. 
  font: false # Prevents autoloading of google fonts, for privacy reasons. 
  favicon: assets/favicon.ico
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - /javascripts/pageview.js



# Plugins
# When you add a plugin here, make sure the change is updated in insiders.mkdocs.yml too. 
plugins:
  - search
  - git-revision-date

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  support_contact: https://amplitude.com
  community: https://community.amplitude.com
  help_site: https://help.amplitude.com
  analytics:
    provider: analytics
    property: amplitude 
  consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
  generator: false #hides the generated with text in the footer

# Navigation
nav:
- Analytics:
  - analytics/index.md
  - Getting Started: 
    - analytics/analytics-domain-proxy.md
  - Amplitude API References:
    - analytics/apis/attribution-api.md
    - analytics/apis/batch-event-upload-api.md
    - analytics/apis/behavioral-cohorts-api.md
    - analytics/apis/chart-annotations-api.md
    - analytics/apis/ccpa-dsar-api.md
    - analytics/apis/dashboard-rest-api.md
    - analytics/apis/export-api.md
    - analytics/apis/group-identify-api.md
    - analytics/apis/http-v2-api.md
    - analytics/apis/identify-api.md
    - analytics/apis/releases-api.md
    - analytics/apis/scim-api.md
    - analytics/apis/taxonomy-api.md
  - Amplitude SDKs:
    - analytics/sdks/sdk-android-overview.md
    - analytics/sdks/sdk-javascript-overview.md
- Experiment:
  - experiment/index.md
- Data: 
  - data/index.md
  - Getting Started:
    - data/getting-started.md
    - data/what-is-a-tracking-plan.md
    - data/creating-your-tracking-plan.md
    - data/working-with-templates.md
    - data/identifying-users-and-groups.md
    - data/best-practices.md
    - data/working-with-branches.md
    - data/typical-workflow.md
    - data/observe.md
    - data/granular-event-destinations.md
    - data/middleware-overview.md
  - Instrumentation:
    - data/ampli-sdk-overview.md
    - data/using-the-ampli-cli.md
    - data/using-the-tracking-library.md
    - data/integrating-with-ci.md
    - data/unit-testing.md
    - data/user-lookup.md
    - data/iglu-api.md
  - Sources:
    - data/browser-ampli.md
    - data/nodejs-ampli.md
    - data/ios-ampli.md
    - data/android-ampli.md
    - data/jre-ampli.md
  - Sources (Legacy):
    - data/browser.md
    - data/nodejs.md
    - data/ios.md 
    - data/android.md
    - data/jre.md
    - data/python.md
    - data/ruby.md 
    - data/dotnet.md
  - Resources:
    - data/managing-your-account.md
    - data/import.md
    - data/integrations.md
    - data/migration-guide.md
  - Integrations:
      - integrations/index.md
      - integrations/analytics-shopify-plugin.md
      - integrations/analytics-recieving-cohorts-from-amplitude.md
- Partner Hub:
  - partners/index.md


            

            
  
  
    
    
    
    
    
    
    
    
    
    
        
    

    


